targets = {
    "You are a cunt. Huge cunt.": 1,
    "Fuck you and fuck your whole family.": 1,
    "Shit. Shit. Shit. Shit.": 1,
    "Did you hear me? You are a bitch": 1, 
    "Bitches ain't shit": 1,
    "Twats are great, I love licking twats": 1,
    "Cocks are great, I love licking cocks": 1,
    "Pussy is great, I love licking pussy": 1,
    "Motherfucker": 1,
    "Tits are great, I love licking tits": 1,
    "Ass is great, I love licking ass": 1,
    "Dicks are great, I love licking dicks": 1,
    "You are a cocksucker": 1,
    "You are a slut": 1,
    "You are a douchenozzle": 1,
    "You are a retard, fuck you": 1,
    "Suck my dick, fuck you": 1,
    "Eat shit and die you worthless piece of shit": 1,
    "Go kill yourself you ugly idiot": 1,
    "Go fuck yourself, bitch": 1,
    "Worthless piece of shit": 1,
    "Burn in hell you bastard!": 1,
    "I'll kill you, whore": 1,
    "I hope you die": 1,
    "I'll fucking murder you": 1,
    "I'll break your neck": 1,
    "Dumbass": 1,
    "Tits": 1,
    "Fucknut": 1,
    "Bollocks": 1,
    "Cockhead": 1,
    "Cunt": 1,
    "Dumbfuck": 1,
    "Numbnuts": 1,
    "Fuckboy": 1,
    "Assclown": 1,
    "Pisshead": 1,
    "Pissbrain": 1,
    "Bastard": 1,
    "Plonker": 1,
    "Dick": 1,
}